from PyQt5.QtCore import Qt
from PyQt5.QtWidgets import *
app = QApplication([])
my_wid = QWidget()
my_wid.setWindowTitle('Второй экран')
my_wid.move(900,70)
my_wid.resize(400,200)
name = QLabel('Введите Ф. И. О.:')
name1 = QLineEdit('')
age = QLabel('Полных лет:')
age1 = QLineEdit('')
text1 = QLabel('Лягте на спину и замерьте пульс за 15 секунд. Нажмите кнопку "Начать первый тест", чтобы запустить таймер.')
text2 = QLabel('Результат запишите в соответствующее поле.')
button1 = QPushButton('Начать первый тест')
pulse = QLineEdit('')
text3 = QLabel('Выполните 30 приседаний за 45 секунд. Для этого нажмите кнопку "Начать делать приседания",')
text4 = QLabel('чтобы запустить счетчик приседаний.')
button2 = QPushButton('Начать делать приседания')
text5 = QLabel('Лягте на спину и замерьте пульс сначала за первые 15 секунд минуты, затем за последние 15 секунд.')
text6 = QLabel('Нажмите на кнопку "Начать финальный тест", чтобы запустить таймер.')
text7 = QLabel('Зеленым обозначены секунды, в течение которых необходимо')
text8 = QLabel('проводить измерения, черным - минуты без замера пульсации. Результаты запишите в соответствующие поля.')
button3 = QPushButton('Начать финальный тест')
pulse1 = QLineEdit('')
pulse2 = QLineEdit('')
timer = QLabel('00:00:15')
v_line = QVBoxLayout()
v_line1 = QVBoxLayout()
v_line.addWidget(name,alignment=Qt.AlignLeft)
v_line.addWidget(name1,alignment=Qt.AlignLeft)
v_line.addWidget(age,alignment=Qt.AlignLeft)
v_line.addWidget(age1,alignment=Qt.AlignLeft)
v_line.addWidget(text1,alignment=Qt.AlignLeft)
v_line.addWidget(text2,alignment=Qt.AlignLeft)
v_line.addWidget(button1,alignment=Qt.AlignLeft)
v_line.addWidget(pulse,alignment=Qt.AlignLeft)
v_line.addWidget(text3,alignment=Qt.AlignLeft)
v_line.addWidget(text4,alignment=Qt.AlignLeft)
v_line.addWidget(button2,alignment=Qt.AlignLeft)
v_line.addWidget(text5,alignment=Qt.AlignLeft)
v_line.addWidget(text6,alignment=Qt.AlignLeft)
v_line.addWidget(text7,alignment=Qt.AlignLeft)
v_line.addWidget(text8,alignment=Qt.AlignLeft)
v_line.addWidget(button3,alignment=Qt.AlignLeft)
v_line.addWidget(pulse1,alignment=Qt.AlignLeft)
v_line.addWidget(pulse2,alignment=Qt.AlignLeft)
v_line1.addWidget(timer,alignment=Qt.AlignRight)
layout_main = QHBoxLayout()
layout_main.addLayout(v_line)
layout_main.addLayout(v_line1)
my_wid.setLayout(layout_main)
my_wid.show()
app.exec_()